### ISSUE TITLE
List all genres / countries

### ISSUE THREAD

**Issue by timpulver** [timpulver/netlabel-list#7]
To simplify the process of spotting misspellings / aliases of genres or countries we could write a node.js script to list all genres / all countries alphabetically, for example:

```
node scripts/list-genres.js
```
This should have an output like:
```
Ambient (87)
Experimental (23)
Experimentaal (1)
...
```

The number in brackets indicates the number of occurrences.

**Comment by michaelGregoire** [comment]
https://github.com/timpulver/netlabel-list/pull/8/commits/61db444c440e8fd7cff78e8ea6cf84925b322114 addresses this
